env: 
#  ENCRYPTED
    RCLONE: "ENCRYPTED[1c856831c6bf80c141e7d12e74f6696672e5a1e19517a7635faaed13d0421c2e6f3d9603efcad29ea698f88222f013f2]"
    
    
#  CIRRUS FLAG
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
       
task:
  name: "Mirror..."
  only_if: $CIRRUS_REPO_OWNER == 'c3eru'
  timeout_in: 1h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G
      
  Environment_script:
      - mkdir -p ~/.config/rclone
      - echo "$RCLONE" > ~/.config/rclone/rclone.conf
      - apt-get update -qqy -y
      - apt-get install --no-install-recommends -y
      - apt-get install wget -y
      - apt-get install zip -y
      - apt-get install unzip -y
      - apt-get autoremove -qqy  -y
      - apt-get autoclean -qqy -y
      - rm -rf /var/lib/apt/lists/*

  Mirror_script:
      - ./mirror.sh
